CREATE TABLE IF NOT EXISTS User (
    userID VARCHAR(64) NOT NULL PRIMARY KEY,
    userType VARCHAR(32) NOT NULL,
    name VARCHAR(64)
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS Accounting (
    ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    userID VARCHAR(64) NOT NULL,
    kind VARCHAR(64) NOT NULL,
    createdTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    accountingTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    price DECIMAL(19, 4) NOT NULL,
    purpose VARCHAR(128) DEFAULT NULL
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;