CREATE TABLE IF NOT EXISTS user (
    user_id VARCHAR(64) PRIMARY KEY,
    user_type VARCHAR(32) NOT NULL,
    name VARCHAR(64)
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS accounting (
    id INT UNSIGNED PRIMARY KEY,
    user_id VARCHAR(64) UNIQUE KEY,
    kind VARCHAR(64),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    accounting_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    price DECIMAL(19, 4),
    purpose VARCHAR(128)
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;